services:
  jekyll:
    image: jekyll/jekyll:4
    container_name: jekyll-site
    working_dir: /srv/jekyll
    command: >
      bash -lc "
      bundle install &&
      jekyll serve
        --host 0.0.0.0
        --livereload
        --force_polling
        --watch
        --incremental
        --config _config.yml,_config_dev.yml
        --baseurl ''
        --url 'http://localhost:4000'
      "
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      JEKYLL_ENV: development
    volumes:
      - ./:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle   # <-- named volume used here
    tty: true
    stdin_open: true

volumes:
  jekyll_bundle: {}   # <-- declare it here
