services:
  jekyll:
    image: jekyll/jekyll:4
    working_dir: /srv/jekyll
    command: sh -c "bundle install && bundle exec jekyll serve \
      --livereload --incremental --drafts --future --host 0.0.0.0 --force_polling \
      --config _config.yml,_config_local.yml"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
volumes:
  bundle_cache:
